export const ACTIONS = {
    GET_ALL_POSTS: 'GET_ALL_POSTS',
    CREATE_POST: 'CREATE_POST',
    UPDATE_POST: 'UPDATE_POST',
    DELETE_POST: 'DELETE_POST',
    LIKE_POST: 'LIKE_POST',
    DISLIKE_POST: 'DISLIKE_POST',
    SET_CURRENT_POST: 'SET_CURRENT_POST',
}